name: pcov
description: >
  The Pinch coverage CLI tool that makes your testing easier. Include untested files and exclude 
  files through your own configuration.
version: 1.0.2
homepage: https://pinch.nl/en
repository: https://github.com/pinchbv/pcov
issue_tracker: https://github.com/pinchbv/pcov/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

executables:
  pcov:

dependencies:
  args: ^2.3.1
  yaml: ^3.1.1
  collection: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
